serve:
  port: 8080
sources:
  - name: Faker
    handler:
      graphql:
        endpoint: http://localhost:9002/graphql
  - name: Apollo
    handler:
      graphql:
        endpoint: http://localhost:4000
  - name: Strapi
    handler:
      graphql:
        endpoint: http://localhost:1337/graphql
