repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  kubeContext: do-fra1-bndigital
  createNamespace: true
  cleanupOnFail: true

environments:
  staging:
    values: [ ]

releases:
  - name: app-react
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: react
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'

  - name: app-vue
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: vue
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'

  - name: app-html
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: html
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'

  - name: app-strapi
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: strapi
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'
      - envSecrets: [ backend-services ]
        configMapsSecrets: [ backend-services ]

  - name: app-graphql
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: graphql
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'
      - image: apisguru/graphql-faker
        app:
          port: 9092

  - name: app-tailwind
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: graphql
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'
      - image: apisguru/graphql-faker
        app:
          port: 9092

  - name: app-storybook
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: storybook
    installed: false
    values:
      - 'values.{{ .Environment.Name }}.gotmpl'
