repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  kubeContext: do-fra1-bndigital
  createNamespace: true
  cleanupOnFail: true

environments:
  staging:
    values: [ ]

releases:
  - name: exabyte-website
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: website
    values:
      - image: dcr.bndigital.dev/exabyte/website:latest
        imagePullSecrets: [ container-registry ]
        podAnnotations:
          git/ref: '{{ env "GITHUB_REF" | default "latest" }}'
          git/sha: '{{ env "GITHUB_SHA" | default "unknown" }}'
        ingress:
          host: exabyte.bndigital.dev
          proxies:
            - path: /(admin|auth|import-export-content|callback|connect|content-manager|content-type-builder|email|email-designer|entity-relationship-chart|i18n|graphql|register|responsive-image|users-permissions|upload|uploads)(.*)
              backend:
                service: grant-mill-cms-nodejs

  - name: exabyte-cms
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/nodejs
    labels:
      app: cms
    values:
      - image: dcr.bndigital.dev/grant-mill/cms:latest
        envSecrets: [ backend-services ]
        configMapsSecrets: [ backend-services ]
        imagePullSecrets: [ container-registry ]
        podAnnotations:
          git/ref: '{{ env "GITHUB_REF" | default "latest" }}'
          git/sha: '{{ env "GITHUB_SHA" | default "unknown" }}'
