# nonk8s
apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
    - image: cms
      docker:
        target: cms
        buildArgs:
          profile: "{{ .SKAFFOLD_PROFILE }}"
          token: "{{ .GITHUB_TOKEN }}"
          endpoint: "{{ .VAULT_ENDPOINT }}"
    - image: website
      docker:
        target: website
        buildArgs:
          profile: "{{ .SKAFFOLD_PROFILE }}"
          token: "{{ .GITHUB_TOKEN }}"
          endpoint: "{{ .VAULT_ENDPOINT }}"
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
    push: true
    useBuildkit: true
profiles:
  - name: staging
    build:
      tagPolicy:
        gitCommit:
          ignoreChanges: true
          variant: CommitSha
