# nonk8s
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: react
    context: packages/website
  - image: strapi
    context: packages/cms
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    concurrency: 0
profiles:
- name: ci
  activation:
  - env: CI=true
  build:
    local:
      push: true
      useBuildkit: true
      concurrency: 0
- name: staging
  activation:
  - kubeContext: do-fra1-bndigital
  build:
    local:
      push: true
      useBuildkit: true
      concurrency: 0
