# nonk8s
apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: website
    context: packages/website
  - image: cms
    context: packages/cms
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    concurrency: 0
test:
  - image: website
    structureTests:
      - container-structure-test.yaml
  - image: cms
    structureTests:
      - container-structure-test.yaml
profiles:
- name: staging
  activation:
  - kubeContext: do-fra1-bndigital
  build:
    local:
      push: true
      useBuildkit: true
      concurrency: 0
    tagPolicy:
      gitCommit:
        variant: CommitSha
        ignoreChanges: true
