# nonk8s
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: vue
    context: packages/vue-website-template
  - image: react
    context: packages/react-antd-website-template
  - image: angular
    context: packages/angular-website-template
  - image: html
    context: packages/html-website-template
  - image: strapi
    context: packages/strapi-cms-template
  - image: tailwind
    context: packages/react-tailwind-website-template
  - image: storybook
    context: packages/react-storybook-template
  - image: apollo
    context: packages/apollo-api-gateway-template
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    concurrency: 0
profiles:
- name: ci
  activation:
  - env: CI=true
  build:
    local:
      push: true
      useBuildkit: true
      concurrency: 0
- name: staging
  activation:
  - kubeContext: do-fra1-bndigital
  build:
    local:
      push: true
      useBuildkit: true
      concurrency: 0
