# nonk8s
apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
    - image: website
      context: packages/website
    - image: cms
      context: packages/cms
      docker:
        buildArgs:
          ENV: '{{ .ENV }}'
  tagPolicy:
    sha256: { }
  local:
    push: true
    useBuildkit: true
    concurrency: 0
test:
  - image: website
    structureTests:
      - container-structure-test.yaml
  - image: cms
    structureTests:
      - container-structure-test.yaml
profiles:
  - name: staging
    activation:
      - kubeContext: do-fra1-bndigital
    build:
      tagPolicy:
        gitCommit:
          variant: CommitSha
          ignoreChanges: true
