# nonk8s
apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
    - image: app
  tagPolicy:
    sha256: { }
  local:
    push: false
    useBuildkit: true
profiles:
  - name: staging
    build:
      tagPolicy:
        gitCommit:
          ignoreChanges: true
          variant: CommitSha
