name: Secrets
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - .github/workflows/secrets.yml
jobs:
  sync:
    name: Infrastructure secrets sync
    runs-on: self-hosted
    steps:
      - name: Set secrets from this repo and organization
        uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            DIGITALOCEAN_TOKEN
            DOCKERHUB_TOKEN
            DOCKERHUB_USERNAME
            DOCKER_PASSWORD
            DOCKER_REGISTRY
            DOCKER_USERNAME
            GH_TOKEN
            KUBERNETES_CLUSTER
            POSTGRESQL_DATABASE
            POSTGRESQL_HOST
            POSTGRESQL_PASSWORD
            POSTGRESQL_PORT
            POSTGRESQL_USERNAME
            SONARQUBE_HOST
            SONARQUBE_TOKEN
            SLACK_WEBHOOK
          REPOSITORIES: |
            ${{ github.repository_owner }}/*
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CONCURRENCY: 10
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          KUBERNETES_CLUSTER: ${{ secrets.KUBERNETES_CLUSTER }}
          POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE }}
          POSTGRESQL_HOST: ${{ secrets.POSTGRESQL_HOST }}
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRESQL_PORT: ${{ secrets.POSTGRESQL_PORT }}
          POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME }}
          SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
