name: Staging
on:
  workflow_dispatch: {}
  push:
    branches:
      - latest
    paths:
      - .github/workflows/staging.yml
      - helmfile.yaml
      - packages/*/Dockerfile
      - packages/*/package.json
      - packages/cms/api/**/*
      - packages/cms/components/**/*
      - packages/cms/config/**/*
      - packages/cms/extensions/**/*
      - packages/website/src/**/*

jobs:
  deploy:
    name: Deploy applications
    environment: staging
    runs-on: self-hosted

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.3.1
        id: secrets
        with:
          url: ${{ secrets.vault_endpoint }}
          method: github
          githubToken: ${{ secrets.gh_token }}
          secrets: |
            infrastructure/data/staging/digitalocean/kubernetes cluster | kubernetes_cluster ;
            infrastructure/data/staging/digitalocean/kubernetes namespace | kubernetes_namespace ;
            infrastructure/data/staging/digitalocean/api token | digitalocean_api_token ;
            infrastructure/data/staging/harbor-registry/docker url | docker_url ;
            infrastructure/data/staging/harbor-registry/docker username | docker_username ;
            infrastructure/data/staging/harbor-registry/docker password | docker_password ;

      - name: Login Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.secrets.outputs.docker_url }}
          username: ${{ steps.secrets.outputs.docker_username }}
          password: ${{ steps.secrets.outputs.docker_password }}

      - name: Setup DigitalOcean cli
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ steps.secrets.outputs.digitalocean_api_token }}

      - name: Configure Kubernetes context
        run: doctl kubernetes cluster kubeconfig save ${{ steps.secrets.outputs.kubernetes_cluster }} --set-current-context

      - name: Build Skaffold artifacts
        uses: hiberbee/github-action-skaffold@1.6.0
        with:
          command: run
          skip-tests: false
          default-repo: ${{ steps.secrets.outputs.docker_url }}/${{ github.event.repository.name }}

      - name: Release Helm charts
        uses: hiberbee/github-action-helm@1.3.0
        env:
          IMAGE_REPOSITORY: ${{ steps.secrets.outputs.docker_url }}/${{ github.event.repository.name }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          helmfile-command: apply
          environment: ${{ steps.secrets.outputs.kubernetes_namespace }}
